version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_CONNECTION_STRING: redis://redis:6379
    ports:
      - "3000:3000"
  redis:
    image: redis:7.0.11
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
